name: Secret scan

on:
  push:
    branches: [ main, starter ]
  pull_request:
    branches: [ main, starter ]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: --report-format json --redact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
